/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jasho9017
 */
public class diceGame extends javax.swing.JFrame {
    int totalRolls = 0;
    int totalCorrect = 0;
    int totalIncorrect = 0;
    int userGuess;
    int diceRoll;
    double percCorrect = 0;

    /**
     * Creates new form diceGame
     */
    public diceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblUserGuess = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        btnRollDice = new javax.swing.JButton();
        lblDiceRoll = new javax.swing.JLabel();
        lblRollValue = new javax.swing.JLabel();
        lblRolls = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("AlgerianBasDEE", 0, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 255));
        lblHeader.setText("super dice guessing game");

        lblInst1.setFont(new java.awt.Font("AlgerianBasDEE", 0, 14)); // NOI18N
        lblInst1.setForeground(new java.awt.Color(0, 0, 255));
        lblInst1.setText("and click roll the dice");

        lblInst2.setFont(new java.awt.Font("AlgerianBasDEE", 0, 14)); // NOI18N
        lblInst2.setForeground(new java.awt.Color(0, 0, 255));
        lblInst2.setText("enter a number from 1 to 6");

        lblUserGuess.setFont(new java.awt.Font("AlgerianBasDEE", 0, 12)); // NOI18N
        lblUserGuess.setForeground(new java.awt.Color(0, 0, 255));
        lblUserGuess.setText("your guess");

        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        btnRollDice.setFont(new java.awt.Font("AdLib Win95BT", 0, 11)); // NOI18N
        btnRollDice.setText("Roll Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        lblDiceRoll.setFont(new java.awt.Font("AlgerianBasDEE", 0, 14)); // NOI18N
        lblDiceRoll.setText("0");

        lblRollValue.setFont(new java.awt.Font("AlgerianBasDEE", 0, 14)); // NOI18N
        lblRollValue.setForeground(new java.awt.Color(0, 0, 255));
        lblRollValue.setText("Dice Roll");

        lblRolls.setFont(new java.awt.Font("AlgerianBasDEE", 0, 12)); // NOI18N
        lblRolls.setForeground(new java.awt.Color(0, 0, 255));
        lblRolls.setText("number of rolls");

        lblIncorrect.setFont(new java.awt.Font("AlgerianBasDEE", 0, 12)); // NOI18N
        lblIncorrect.setForeground(new java.awt.Color(0, 0, 255));
        lblIncorrect.setText("number of incorrect rolls");

        lblCorrect.setFont(new java.awt.Font("AlgerianBasDEE", 0, 12)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(0, 0, 255));
        lblCorrect.setText("number of correct rolls");

        lblPercent.setFont(new java.awt.Font("AlgerianBasDEE", 0, 12)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(0, 0, 255));
        lblPercent.setText("percentage of correct rolls");

        lblRollsValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRollsValue.setText("0");

        lblCorrectValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorrectValue.setText("0");

        lblIncorrectValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIncorrectValue.setText("0");

        lblPercentValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPercentValue.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblInst1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInst2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRollDice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPercent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRollValue)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIncorrect)
                                        .addComponent(lblRolls, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCorrect)
                                        .addComponent(lblDiceRoll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUserGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserGuess))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRollValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRollDice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRolls, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRollsValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorrectValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncorrect)
                    .addComponent(lblIncorrectValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercent)
                    .addComponent(lblPercentValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserGuessActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        diceRoll = (int)Math.round(Math.random()*5+1);
        lblDiceRoll.setText(String.valueOf(diceRoll));
        userGuess = Integer.parseInt(txtUserGuess.getText());
        totalRolls = totalRolls+1;
        
        if (diceRoll == userGuess)
        {
            totalCorrect = totalCorrect+1;
        }
        else
        {
            totalIncorrect = totalIncorrect+1;
        }    
        
        percCorrect = ((double)totalCorrect/(double)totalRolls)*100;
        
        percCorrect = percCorrect*100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect/100;
        
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect));
        
    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
